version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch-browsers
    steps:
      - checkout
      - run:
          name: Create virtual environment
          command: |
            python3 -m venv venv
      - run:
          name: Install requirements
          command: |
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r tests/requirements.txt
            pip install codecov
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make test-strict
            make coverage
      - store_artifacts:
          path: .coverage-html/
